print(" ------------------------------------------------")
print("|                                                |")
print("|    01HelloWorld                                |")
print("|    Name : Lia Wigglesworth                     |")
print("|    Version : 01                                |")
print("|                                                |") 
print(" ------------------------------------------------")
print("Hello World")