print(" ------------------------------------------------")
print("|                                                |")
print("|    02GoodbyeWorld                              |")
print("|    Name : Lia Wigglesworth                     |")
print("|    Version : 01                                |")
print("|                                                |") 
print(" ------------------------------------------------")
print("Hello World")
username = input("------> Program paused - press enter to continue")
print("Goodbye World")